#!/usr/bin/python3

import subprocess as sub
import time

experiment_time = 10

settings = [
    { 
        'frame_rate' : 30,
        'quantizer' : 16,
        'delay' : 1
    },
    { 
        'frame_rate' : 15,
        'quantizer' : 16,
        'delay' : 1
    },
    { 
        'frame_rate' : 6,
        'quantizer' : 16,
        'delay' : 1
    },
]

for setting in settings:
    print(setting)
    p = sub.Popen(['./ps4_degrader', 
                   '-d', '0', 
                   '-m', '14',
                   '-p', '3',
                   '-v', 'video.raw',
                   '-l', '/dev/null'
                   '-b', str(2**20),
                   '-f', str(60 / setting['frame_rate']),
                   '-q', str(setting['quantizer']),
                   '-D', str(setting['delay']),
                   '-B', 'beforeFile.raw',
                   '-A', 'afterFile.raw'],
#                   stderr=open('cerr.log', 'w'),
                   stdout=open('cout.log', 'w'))

    time.sleep(experiment_time)
    p.kill()
    input(str(experiment_time) + ' seconds have elasped. Press [ENTER] to continue')
